# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

name: $(BuildDefinitionName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  - group: android_cicd
  - name: buildConfiguration
    value: 'Release'
  - name: outputDirectory
    value: '$(build.ArtifactStagingDirectory)/$(buildConfiguration)'

# trigger:
# - none
pr:
- master

stages:

- stage:
  displayName: "Build Stage"

  jobs:

  - job:
    displayName: "build and release andoroid app job"

    pool:
      vmImage: 'windows-2019'
      demands:
      - 'MSBuild'
      - 'Xamarin.Android'
      - 'JDK'

    steps:
    - task: NuGetToolInstaller@0
      displayName: 'Install NuGet tool version 4.4.1'
      inputs:
        versionSpec: 4.4.1

    - task: NuGetCommand@2
      displayName: 'Restore NuGet packages'
      inputs:
        command: restore
        restoreSolution: '**/ayuina-xamarin-helloapp.sln'
        feedsToUse: 'select' 
        vstsFeed: $(artifact_feed) 

    - task: 'richardfennellBM.BM-VSTS-Versioning-Task.Version-AndroidManifest-Task.VersionAndroidManifest@2'
      displayName: 'Define apk version'
      inputs:
        VersionNumber: "DummyVersion_1.0.0"
        Injectversioncode: true
        VersionCode: '$(Build.BuildId)'

    - task: XamarinAndroid@1
      displayName: 'Build Xamarin.Android project'
      inputs:
        projectFile: '**/HelloApp.XamarinAndroid.csproj'
        outputDirectory: '$(outputDirectory)'
        configuration: '$(buildConfiguration)'
        jdkVersionOption: 1.8

    - task: DownloadSecureFile@1
      displayName: 'Download keytore'
      inputs:
        secureFile: '$(apksignerKeystore_filename)'

    - task: AndroidSigning@3
      displayName: 'Sign and Zipalign apk'
      inputs:
        apkFiles: '$(outputDirectory)/**/*.apk'
        apksign: true
        apksignerKeystoreFile: '$(apksignerKeystore_filename)'
        apksignerKeystorePassword: '$(apksignerKeystorePassword)'
        apksignerKeystoreAlias: '$(apksignerKeystoreAlias)'
        apksignerKeyPassword: '$(apksignerKeyPassword)'
        zipalign: true

    - task: MSBuild@1
      displayName: 'build test project'
      inputs:
        solution: '**/HelloApp.XamarinAndroid.Test.csproj'
        configuration : $(buildConfiguration)
        msbuildArguments: '/p:JavaSdkDirectory="$(JAVA_HOME_8_X64)" /p:OutDir="$(outputDirectory)"'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifact'
      inputs:
        PathtoPublish: '$(outputDirectory)'

    - task: AppCenterDistribute@2
      displayName: 'Push to AppCenter Release'
      inputs: 
        serverEndpoint: '$(appcenter_serverendpointname)'
        appSlug: '$(appcenter_appslug)'
        appFile: '$(outputDirectory)/**/*.apk'
        symbolsIncludeParentDirectory: false
        releaseNotesInput: 'Builded By Azure Pipeline - $(Build.BuildNumber)'
        isMandatory: true
        distributionGroupId: '$(appcenter_distributionGroupId)'

    - powershell: 'dir env:'

    - powershell: 'get-childitem -Path "$env:userprofile/.nuget/packages/xamarin.uitest/" -Recurse'

    - task: AppCenterTest@1
      inputs:
        appFile: '$(outputDirectory)/**/*.apk'
        artifactsDirectory: '$(outputDirectory)/AppCenterTest'
        prepareTests: true
        frameworkOption: uitest
        uiTestBuildDirectory: $(outputDirectory)
        runTests: true
        credentialsOption: 'serviceEndpoint'
        serverEndpoint: '$(appcenter_serverendpointname)'
        appSlug: '$(appcenter_appslug)'
        devices: '$(appcenter_testdevices)'
        series: master
        uiTestToolsDirectory: '$(userprofile)/.nuget/packages/xamarin.uitest/2.2.7/tools'
        localeOption: 'en_US'