
name: $(BuildDefinitionName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  - group: android_cicd
  - name: buildConfiguration
    value: 'Release'
  - name: outputDirectory
    value: '$(build.ArtifactStagingDirectory)/$(buildConfiguration)'

trigger:
- none

stages:

- stage:
  displayName: 'Build and Test stage'
  jobs:
  - job:
    pool:
      vmImage: 'windows-2019'
      demands:
      - 'MSBuild'
      - 'Xamarin.Android'
      - 'JDK'

    steps:
    - task: NuGetToolInstaller@0
      displayName: 'Install NuGet tool version 4.4.1'
      inputs:
        versionSpec: 4.4.1

    - task: VisualStudioTestPlatformInstaller@1
      displayName: 'install vstest platform'

    - task: NuGetCommand@2
      displayName: 'Restore NuGet packages'
      inputs:
        restoreSolution: '**/ayuina-hello-classlibrary.sln'

    - task: MSBuild@1
      displayName: 'build test project'
      inputs:
        solution: '**/ayuina-hello-classlibrary.sln'
        configuration : $(buildConfiguration)
        msbuildArguments: '/p:OutputPath="$(outputDirectory)" /p:JavaSdkDirectory="$(JAVA_HOME_8_X64)"'

    - task: VSTest@2
      displayName: 'run unit test'
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: '$(outputDirectory)/**/*.Tests.dll'

    - task: MSBuild@1
      displayName: 'build dll project'
      inputs:
        solution: '**/ayuina-hello-classlibrary.sln'
        configuration : $(buildConfiguration)
        msbuildArguments: '/p:JavaSdkDirectory="$(JAVA_HOME_8_X64)"'

    - task: NuGetCommand@2
      displayName: 'NuGet pack'
      inputs:
        command: pack
        packagesToPack: '**/HelloApp.ClassLibrary.csproj'
        configuration: '$(BuildConfiguration)'
        packDestination: '$(outputDirectory)'
        versioningScheme: byPrereleaseNumber
        majorVersion: 1
        minorVersion: 0
        patchVersion: 0

    - task: NuGetCommand@2
      displayName: 'NuGet push'
      inputs:
        command: push
        nuGetFeedType: 'internal'
        publishVstsFeed: $(artifact_feed)
        packagesToPush: '$(outputDirectory)/**/*.nupkg'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifact'
      inputs:
        PathtoPublish: '$(outputDirectory)'

